    - platform: command_line
      switches:
        switch_topeni:
          command_on: '/usr/bin/curl -X GET http://192.168.2.2:8181/sdscep?sys148=111'
          command_off: '/usr/bin/curl -X GET http://192.168.2.2:8181/sdscep?sys148=0'
          command_state: /usr/bin/curl -X GET http://192.168.2.2:8181/usys.xml 2>&1 | grep -Po "(?<=<sys148>).*(?=</sys148>)"
          value_template: '{{ value == "111" }}'



    - platform: command_line
      switches:
        switch_rele1:
          command_on: "/usr/bin/curl -X GET http://192.168.2.2:8181/sdscep?sys147=111"
          command_off: "/usr/bin/curl -X GET http://192.168.2.2:8181/sdscep?sys147=0"
          command_state: "/usr/bin/curl -X GET http://192.168.2.2:8181/xml.xml 2>&1 | grep -Po '(?<=<relay_1>).*(?=</relay_1>)'"
          value_template: '{{ value == "255" }}'

    - platform: command_line
      switches:
        switch_rele2:
          command_on: "/usr/bin/curl -X GET http://192.168.2.2:8181/sdscep?sys148=111"
          command_off: "/usr/bin/curl -X GET http://192.168.2.2:8181/sdscep?sys148=0"
          command_state: "/usr/bin/curl -X GET http://192.168.2.2:8181/xml.xml 2>&1 | grep -Po '(?<=<relay_2>).*(?=</relay_2>)'"
          value_template: '{{ value == "255" }}'
   
    - platform: mqtt
      name: Topeni jezirko
      command_topic: "/ESP_jezirko_topeni/rele/switch/command"
      state_topic: "/ESP_jezirko_topeni/rele/switch"
      qos: 0
      payload_on: "on"
      payload_off: "off"
      state_on: "1"
      state_off: "0"
      retain: false

    - platform: command_line
      switches:
        switch_topeni_jezirko:
          command_on: "/usr/bin/curl -X GET http://192.168.2.144/control?cmd=event,ZapniRele"
          command_off: "/usr/bin/curl -X GET http://192.168.2.144/control?cmd=event,VypniRele"
#          command_state: "/usr/bin/curl -X GET http://192.168.10.168/control?"
#          value_template: '{{ value == "1" }}'
