#zone:
   - name: Skola 
     latitude: 49.826127
     longitude: 18.127924
     radius: 50
     icon: mdi:school

   - name: Tieto
     latitude: 49.8306841
     longitude: 18.2779021
     radius: 100
     icon: mdi:worker

   - name: D_Lhota
     latitude: 49.8406339
     longitude: 18.0823200
     radius: 15
     elevation: 234
     icon: mdi:home

#   - name: Vresina
#     latitude: 49.8287805
#     longitude: 18.1153765
#     radius: 20
#     icon: mdi:account-heart


   - name: Obecni urad_Lhota
     latitude: 49.8401953
     longitude: 18.0919205
     radius: 10
     icon: mdi:account-heart

