esphome:
  name: esp-topeni-vresina-2p

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "0KWtlMXEDU3YMTm406nyyj2T634sJnRFpFdZg5sYJMA="

ota:
  password: "626d9537d7ecea7bea902c252602319e"

wifi:

  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid_2
      password: !secret wifi_password2
      
#  use_address: esp-topeni-vresina-2p.hruzik.net
  use_address: 192.168.2.171
#  use_address: 192.168.10.248  
# mac: 60:01:94:09:AF:11  
    
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Topeni-Vresina-2P"
    password: "Pepanek1976!"


web_server:
  port: 80
  
improv_serial:
captive_portal:

  # Example configuration entry
dallas:
  - pin: GPIO2
    update_interval: 10s
    
sensor:
  - platform: dallas
    address: 0x090000072a0eab28
    name: "Dallas_2_patro_temp"

    
  - platform: dht
    pin: GPIO0
    model: DHT22
    temperature:
      name: "DHT22_2_patro_temp"
    humidity:
      name: "DHT22_2_patro_humidity"
    update_interval: 10s    
    