esphome:
  name: esp32-vresina-1p

esp32:
  board: esp32cam
  framework:
    type: arduino



wifi:

  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid_2
      password: !secret wifi_password2
      
  use_address: 192.168.2.175
#mac: 3C:71:BF:AF:C1:14
  
  
#  manual_ip:
#    static_ip: 192.168.10.173
#    gateway: 192.168.10.1
#    subnet: 255.255.255.0
#    dns1: 192.168.10.230
#    dns2: 8.8.8.8

api:
logger:
ota:
  password: "8147176ea43fedb00ff6a75f80bd3f7e"
  
  

web_server:
  port: 80
  
improv_serial:
captive_portal:

dashboard_import:
  package_import_url: github://esphome/bluetooth-proxies/esp32-generic.yaml@main

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:

button:
- platform: safe_mode
  name: Safe Mode Boot
  entity_category: diagnostic
  
  # Example configuration entry
dallas:
  - pin: GPIO2
    update_interval: 10s
sensor:
  - platform: dallas
    address: 0x710000065cf35628
    name: "ESP2Temp"
    

  - platform: atc_mithermometer
    mac_address: "A4:C1:38:E8:DF:96"
#    bindkey: "01e748a6f63d392ce197bc6d0a549642"
    temperature:
      name: "ATC Temperature"
    humidity:
      name: "ATC Humidity"
    battery_level:
      name: "ATC Battery-Level"
    battery_voltage:
      name: "ATC Battery-Voltage"
    signal_strength:
      name: "ATC Signal"
    
